### ISSUE TITLE
Help: How to render with a MVP Matrix 

### ISSUE THREAD

**Issue by lehmamic** [mellinoe/veldrid#53]
Hi,

I'm trying to make the OpenGL Tutorials by using Veldrid and I'm stuck a bit.

Currently I'm experimenting with the matrices tutorial:
http://www.opengl-tutorial.org/beginners-tutorials/tutorial-3-matrices/

I can pass the MVP matrix to the vertex shader, but as soon as I'm applying it to the position vertex I can't see anything anymore.
https://github.com/lehmamic/VedridExercises/tree/Tutorial-3--Matrices

Could you please give me a hint what is wrong? Thanks.

**Comment by geoeo** [comment]
Your camera matrix looks a but dodgy. Your vertex points are around (0,0,0) but your camera is at (4,3,3). It might be that your camera is above the triangle. Try recentering at (0,0,1) for example.

**Comment by mellinoe** [comment]
@lehmamic There were a few problems. I fixed them and then I was able to get the triangle rendering.

Veldrid doesn't support "naked" uniform values in OpenGL shaders -- you have to wrap them in a uniform block. Your vertex shader should look like this:

```GLSL
#version 330 core

in vec3 Position;
in vec4 Color;

layout(std140) uniform MVP
{
    mat4 MvpMatrix;
};

void main()
{
    gl_Position = MvpMatrix * vec4(Position, 1);
}
```

You were concatenating your MVP matrix in the wrong order. It should be:

```C#
Matrix4x4 mvp = model * view * projection;
```

In your Pipeline description, you are using `DepthStencilStateDescription.DepthOnlyLessEqual`, but you aren't creating a depth attachment for the main swapchain (which is your render target). There's two fixes possible:

1. Simply use `DepthStencilStateDescription.Disabled`.
2. Specify a depth format when creating the main swapchain. This is done by passing a `GraphicsDeviceOptions` into `CreateWindowAndGraphicsDevice`. The options structure should specify a valid value for `SwapchainDepthFormat`, like `R16_UNorm`. In your render loop, call `commandList.ClearDepthStencil(1);`.

Number 1 is easier, so just do that for now.

@geoeo mentioned that the camera is in an odd position, but the triangle is still visible from that spot, it's just a bit skewed. So it should be fine as-is.

**Comment by mellinoe** [comment]
By the way, I was able to quickly identify the problems by running your app under [RenderDoc](https://renderdoc.org/). It was clear that the MVP uniform wasn't getting set, so I checked that first. Then, the vertex output was wrong, so I checked how you were creating the MVP matrix (and discovered the multiplication order problem).

**Comment by lehmamic** [comment]
Thanks @mellinoe . With your hints it works. 
The uniform blocks (I misunderstood it in your docs because you mentioned uniform variables for GLSL) and the Depth Stencil I understand.

What confuses me is the wrong ordering of my MVP calculation. In the tutorial there is following c++ code, which works on my machine:
`glm::mat4 mvp = Projection * View * Model;`

I didn't find any documentation that Matrix4x4 multiplication is is the opposite order.

@geoeo I just took the values from the tutorial. Generally it should not be a matter where the camera is located as long as it looks to the place where the model is located. The model is at the world origin and the camera also looks at this point. Thats why I was quite sure that it isn't my camera settings.

**Comment by mellinoe** [comment]
@lehmamic It seems that glm uses column-major matrices where System.Numerics uses row-major matrices. That will reverse the order of multiplication as far as I understand.

**Comment by lehmamic** [comment]
I recognised that already, but assumed the multiplication is the same. That would explain it. Thanks.

**Comment by mellinoe** [comment]
I think this one is resolved now. Let me know if you have any further questions.

**Comment by lehmamic** [comment]
Yes I think you can close it.

I have some more questions:
When I have several meshes or sprites to draw, do I always need a dedicated pipeline per model? Or how can I do it with the different textures required for the model?

When I render text, do I always need to have a dedicated vertex/index buffer for each text to render and dispose it afterwards?

**Comment by mellinoe** [comment]
> When I have several meshes or sprites to draw, do I always need a dedicated pipeline per model? Or how can I do it with the different textures required for the model?

You only need a different Pipeline if the pipeline state would be different between them. For sprites, this will not be the case, typically, so you can use the same Pipeline.

To draw different textures, you have a few different options. Textures are bound to a Pipeline via ResourceSets, and they are not part of the Pipeline state itself (so you can use many different ResourceSets with the same Pipeline). A Pipeline and a ResourceSet need to share a _ResourceLayout_ to be compatible. A ResourceLayout which describes the types of resources contained in a ResourceSet or used by a Pipeline.

Some options for drawing different Textures with the same Pipeline:

1. Bind different ResourceSets to your CommandList before issuing a Draw command. This is the obvious, straightforward way to do it. Each different Texture would have its own ResourceSet.
2. Create a [texture atlas](https://en.wikipedia.org/wiki/Texture_atlas) and upload it into a single Veldrid Texture and put it in a ResourceSet. When drawing, now your sprites need to know which subregion of the texture atlas corresponds to the data they should sample. Typically you would do that by binding a uniform buffer and reading that data in the shader.
3. If all of your textures are the same size, you could create an array texture and put each sprite into its own array layer. This is basically just number (2) except it's simpler to reason about since each image would be shoved into its own dedicated layer and thus separated from the others.

> When I render text, do I always need to have a dedicated vertex/index buffer for each text to render and dispose it afterwards?

You shouldn't need to do that. You can re-use the buffers and re-use the data if you want. When you issue draw commands, you can specify a base vertex and base index, so your data doesn't necessarily have to start from the beginning of your buffers.

If you know you're going to need another vertex/index buffer, then it will be much more efficient to keep them around rather than disposing/recreating them, which can be expensive.

**Comment by lehmamic** [comment]
The texture question is clear now, but I'm still not really sure about the buffers. I agree it is better to reuse them instead of recreating them, thats why I'm asking. Do I understand it correctly that you would create a large buffer (not only sized to you vertices/indices) and put the data always on the last part of it so that this base index can be used?

btw. thanks for the RenderDoc hint, this was already very helpful, just a patty that it does not run on mac.

**Comment by mellinoe** [comment]
> Do I understand it correctly that you would create a large buffer (not only sized to you vertices/indices) and put the data always on the last part of it so that this base index can be used?

Roughly speaking, yes. If you won't use the data at the beginning of the buffer again, though, then you can just overwrite it for subsequent draws.

The way ImGui is drawn is pretty similar here, because it uses new vertex / index data every frame.

https://github.com/mellinoe/veldrid/blob/master/src/Veldrid.ImGui/ImGuiRenderer.cs#L411-L444

At a high level, it works like this:

* To start, create a "fairly large" buffer for vertices and indices. For the default size here, I just experimented with "normal uses" and checked how big the vertex/index data needed to be.
* Each frame, ImGui gives you new vertex/index data. If the data fits in the existing buffers, then just copy it in.
* If the data doesn't fit into the buffers, then dispose the old ones and make a slightly bigger one.
* To avoid continuous resizes, the new buffers are 1.5x the needed size. This means you have a little bit of wiggle room if the data size increases a bit.

> btw. thanks for the RenderDoc hint, this was already very helpful, just a patty that it does not run on mac.

Yeah, debugging on mac is a bit of a pain. Xcode has a decent debugger for Metal, but I have found that it is a bit more unstable than RenderDoc is. Also, I find the UI to be a bit of a nightmare, so it's kind of hard to navigate around to the data you are interested in, compared to RenderDoc 😅

**Comment by lehmamic** [comment]
Thanks for the hint, i'll try it out.

Do you know [Pfim](https://nickbabcock.github.io/Pfim/)? I managed to load DDS textures in combination with your ImageSharpTexture. With some problems but basically it worked. It could be an option for you to provide DDS and TGA support.

**Comment by mellinoe** [comment]
Pfim looks pretty nice; we definitely need more options when it comes to managed image loading. Ideally you would be able to load up the raw compressed data from the DDS images to put into a Veldrid Texture, but that doesn't look possible with the current API. It seems you have to decompress into a 24-bit or 32-bit RGB/RGBA buffer. Still, it looks like a pretty good start.
